////////////////////////////////////////////////////////////////////////////////
Copyright (c) 2012, THE BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIOR UNIVERSITY
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   Neither the name of the STANFORD UNIVERSITY nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////

= Service Contract: ServiceBroker
:toc:

== Document Version
1.0

== Intent
The intent of this document is to provide a contract for consumer reference on use of this service.

== Name
ServiceBroker

== Description
This service is the base implementation of a broker for STROMA compliant services. The functionality enabled for STROMA compliant services by the ServiceBroker service are as follows:

* Request/Response batching
* Synchronous/Asynchronous request capabilities
* Service chaining
* Adapter mechanism for additional service request transport protocol support 
* General service orchestration, local and remote

== Owner
TBD

== Service Handle
servicebroker

== Service Capabilities
* Self

== Interface

=== Interface Classification
* asynchronous/synchronous
* X-STROMA compliant (STROMA brokering spec)
* HTTP

[NOTE]
Please see the STROMA/X-STROMA specification along with the Cyclades Service Engine specification for the most up to date details of this service.

== Functional Requirements
* The ServiceBroker will deliver functionality to realize the following capabilities
- Request/Response batching
- Synchronous/Asynchronous request capabilities
- Service chaining
- Adapter mechanism for additional service request transport protocol support
- General service orchestration, local and remote

== Non Functional Requirements

* SLA/QoS
 - N/A

* Security
 - N/A
