////////////////////////////////////////////////////////////////////////////////
Copyright (c) 2012, THE BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIOR UNIVERSITY
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   Neither the name of the STANFORD UNIVERSITY nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////

= Service Profile: ServiceBroker
:toc:

== Document Version
1.0

== Intent
The intent of this document is to provide an overview and meta data for the discovery of this service and its capabilities. This document should be comprehensible to all stakeholders. This document may also be indexed and used to aid in service discovery. An access route can be utilized via tha Service Registry home page.

== Name
ServiceBroker

== Purpose

=== Short
The purpose of this service is to broker service requests and responses. In short, this service can be utilized to request STROMA compliant services in different ways.

=== Detailed
This service is the base implementation of a broker for STROMA compliant services. The functionality enabled for STROMA compliant services by the ServiceBroker service are as follows:

* Request/Response batching
* Synchronous/Asynchronous request capabilities
* Service chaining
* Adapter mechanism for additional service request transport protocol support
* General service orchestration, local and remote

== Service Model 
Utility(STROMA compliant Service Orchestration)

== Tags
broker, message, orchestration, chain, transformation, batch, content, generation, asynchronous, multiplexing

== Owner
TBD

== Status
Service is complete

== Deployment Overview

=== Service Handle
servicebroker

=== Interface Classification
* asynchronous/synchronous
* X-STROMA compliant (STROMA brokering spec)
* HTTP adapter is included with default installation

=== Dependencies On Other Services
None

=== Deployment Location
All tiers, this service is intentded to be part of every base installation of the services engine.
