////////////////////////////////////////////////////////////////////////////////
Copyright (c) 2012, THE BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIOR UNIVERSITY
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   Neither the name of the STANFORD UNIVERSITY nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////

= Service Profile: NYXLET_NAME
:toc:

[red yellow-background]#IMPORTANT: Please update this document and remove this directive when you are done#

== Document Version
1.0

== Intent
The intent of this document is to provide an overview and meta data for the discovery of this service and its capabilities. This document may also be indexed and used to aid in service discovery. An access route can be utilized via the Service Registry home page.

== Name
NYXLET_NAME

== Purpose

=== Short
<short purpose description goes here>

=== Detailed
<detailed purpose description goes here>

== Service Model 
<one of utility, entity, task...etc...>

== Tags
<tags go here, i.e. authorization, authentication, user, priv, token...etc>

== Owner
TBD

== Status
*IN PROGRESS*

== Deployment Overview

=== Service Handle
NYXLET_NAME

=== Protocol/Interface Classification
* synchronous
* STROMA compliant (Transport Protocol Agnostic)
* HTTP adapter is included with default installation

=== Dependencies On Other Services And/Or Resources
<Any services or resources that this service depends on get listed here. Please remove and replace the sample entries.>

.Dependencies
[options="header"]
|=========================================================
|Classification			|Name				|Notes
|Service/Nyxlet			|xsl				|N/A
|Service/HTTP (non-Nyxlet)	|my content service		|http://foo.mycompany.org/mycontent
|Database			|mysql cluster			|mysql, (maybe list the servers per environment here if applicable)
|=========================================================

=== Deployment Location
<The environments and clusters that this service is/will be deployed to go here>

== Service Capabilities

.Capabilities/Actions
[options="header"]
|=========================================================
|Action				|Purpose				|Tags					|Status
|sayhello			|Example of bare bones action handler	|sayhello, simple			|Complete
|=========================================================

== Modifications To This Document

[options="header"]
|=========================================================
|Author			|Date		|Version	|Details
|<name>			|<date>		|1.0		|Document Creation
|=========================================================
