////////////////////////////////////////////////////////////////////////////////
Copyright (c) 2012, THE BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIOR UNIVERSITY
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   Neither the name of the STANFORD UNIVERSITY nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////

= Capability Functional Test Results
:toc:

[red yellow-background]#IMPORTANT: Please update this document and remove this directive when you are done#

== Document Version
1.0

== Intent
The intent of this document is to provide a record for consumer reference on functional testing results of this capability

== Name
sayhello

== Test Runs

=== Test Case 111

==== Date
4/14/12

==== Objective
Sample functional test for this capability.

We're simply looking for the following response:
----
<response service="NYXLET_NAME" action="sayhello" error-code="0">
<message>Hello World: [foo]</message>
</response>
----

==== Request Format

----
http://localhost:8080/cyclades/NYXLET_NAME?action=sayhello&name=foo&data-type=xml
----

==== Environment Details

* Pool 
	** N/A
* Load Balancer Details
	** N/A
* Servers
	** localhost
	** VM
	** 3 Gigs Memory
	** 100 Gigs Disk

==== Test Details

Any test setup details go here

==== Test Results

Test results go here

We received the following response....so technically we have passed!
----
<response service="NYXLET_NAME" action="sayhello" error-code="0">
<message>Hello World: [foo]</message>
</response>
----

==== Assessment

[green]#Passed#

== Modifications To This Document

[options="header"]
|=========================================================
|Author			|Date		|Version	|Details
|<name>			|<date>		|1.0		|Document Creation
|=========================================================
