////////////////////////////////////////////////////////////////////////////////
Copyright (c) 2012, THE BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIOR UNIVERSITY
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   Neither the name of the STANFORD UNIVERSITY nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////

= Service Registry

== Document Version
1.0

== Intent
The intent of this document is to provide a registry for services. This document  should be comprehensible to all stakeholders.

== Owner
TBD

.Services
[options="header"]
|========================================
|Service	|Handle	|Artifacts
|HelloWorld|helloworld|link:HelloWorld/service_profile.html[profile] \| link:HelloWorld/service_contract.html[contract]
|ServiceBroker|servicebroker|link:ServiceBroker/service_profile.html[profile] \| link:ServiceBroker/service_contract.html[contract]
|========================================

.Service Engines
[options="header"]
|========================================
|Name	|Links
|Local Engine Instance|http://localhost:8080/cycladesengine[Status] \| http://localhost:8080/cycladesengine?action=loaded[Inventory] \| http://localhost:8080/cycladesengine?action=health[Health] \| http://localhost:8080/cycladesengine?action=reload[Reload] \| http://localhost:8080/cycladesengine?action=memory[Memory] \| http://localhost:8080/cycladesengine?action=memorywithgc[GC]
|========================================



