////////////////////////////////////////////////////////////////////////////////
Copyright (c) 2012, THE BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIOR UNIVERSITY
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   Neither the name of the STANFORD UNIVERSITY nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////

= Service Capablity Contract: orchestratesayhellobroker
:toc:

== Document Version
1.0

== Intent
The intent of this document is to provide a contract for consumer reference on use of this capability

== Name
orchestratesayhellobroker

== Description
This capability is meant to be used as an example of how to make a brokered service request from within a service.

== State Management
This service capability is stateless

== Owner
TBD

== Interface

=== Interface Classification
* STROMA
* synchronous

=== Expected Input

.Special URI rules

* N/A

.Parameters

* *broker-target* [optional] This parameter, if set, will set the target on the service broker to this value. Leave this out to default to local engine.

.Meta Data

* N/A

==== XML request variations
[NOTE]
This is just a simple exmple for reference. Please see STROMA specification for details.
----
http://localhost:8080/cycladesengine/helloworld?action=orchestratesayhellobroker&data-type=xml&broker-target=localhost
----

==== JSON request variations
[NOTE]
This is just a simple exmple for reference. Please see STROMA specification for details.
----
http://localhost:8080/cycladesengine/helloworld?action=orchestratesayhellobroker&data-type=json&broker-target=localhost
----

=== Expected Output

==== XML
----
<response service="helloworld" action="orchestratesayhellobroker" error-code="0" ><map message="Brokered request 1:[Hello World: [DEFAULT_EXAMPLE_NAME] ] Brokered request 2:[Hello World: [EXAMPLE_NAME_1] ] Brokered request 3:[Hello World: [EXAMPLE_NAME_2] ] Brokered request 4:[Hello World: [EXAMPLE_NAME_3] ] Brokered request 5:[Hello World: [EXAMPLE_NAME_4] ] Brokered request 6:[Hello World: [EXAMPLE_NAME_5] ] Brokered request 7:[Hello World: [EXAMPLE_NAME_6] ] Brokered request 8:[Hello World: [EXAMPLE_NAME_7] ] Brokered request 9:[Hello World: [EXAMPLE_NAME_8] ] Brokered request 10:[Hello World: [EXAMPLE_NAME_9] ] "></map></response>
----

==== JSON
----
{"service":"helloworld","action":"orchestratesayhellobroker","error-code":"0","data":{"message":"Brokered request 1:[Hello World: [DEFAULT_EXAMPLE_NAME] ] Brokered request 2:[Hello World: [EXAMPLE_NAME_1] ] Brokered request 3:[Hello World: [EXAMPLE_NAME_2] ] Brokered request 4:[Hello World: [EXAMPLE_NAME_3] ] Brokered request 5:[Hello World: [EXAMPLE_NAME_4] ] Brokered request 6:[Hello World: [EXAMPLE_NAME_5] ] Brokered request 7:[Hello World: [EXAMPLE_NAME_6] ] Brokered request 8:[Hello World: [EXAMPLE_NAME_7] ] Brokered request 9:[Hello World: [EXAMPLE_NAME_8] ] Brokered request 10:[Hello World: [EXAMPLE_NAME_9] ] "}}
----

== Additional Orchestration Capability Details

None

== Functional Requirements

* This capability will demonstrate that a developer of a service could make a service broker request from within a service.

== Non Functional Requirements

* SLA/QoS
 - N/A

* Security
 - N/A
