////////////////////////////////////////////////////////////////////////////////
Copyright (c) 2012, THE BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIOR UNIVERSITY
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   Neither the name of the STANFORD UNIVERSITY nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////

= Service Capablity Contract: sayhello
:toc:

== Document Version
1.0

== Intent
The intent of this document is to provide a contract for consumer reference on use of this capability

== Name
sayhello

== Description
This capability is meant to be used as a template. It simply prints out a "Hello World" message.

== State Management
This service capability is stateless

== Owner
TBD

== Interface

=== Interface Classification
* STROMA
* synchronous

=== Expected Input

.Special URI rules

* N/A

.Parameters

*name* [optional] A name to append to the end of the Hello World message. Multiple values will be appended as well.

.Meta Data

Meta data for this capability is optional. The meta data, if present, will consist of an additional message that will be appended to the end of the Hello World message. The following are examples of what the meta data format will look like for XML and JSON, respectively:

[NOTE]
*parameters* has been added in the examples for reference. *parameters* is a reserved field, please see the STROMA/X-STROMA specification for more details.

----
<data><parameters/><message value="xxx"></data>
----

----
{"parameters":[],"message":"xxx"}
----

[NOTE]
The following are trivial examples to use as a reference. Please see STROMA/X-STROMA specification for details.

==== XML request variations
----
http://localhost:8080/cycladesengine/helloworld?action=sayhello&name=Tom&data-type=xml&data=<data><parameters/><message value="xxx"/></data>
----

==== JSON request variations
----
http://localhost:8080/cycladesengine/helloworld?action=sayhello&name=Tom&data-type=json&data={"parameters":[],"message":"xxx"}
----

=== Expected Output

==== XML
----
<response service="helloworld" action="sayhello" error-code="0" ><map message="Hello World: [Tom] xxx"></map></response>
----

==== JSON
----
{"service":"helloworld","action":"sayhello","error-code":"0","data":{"message":"Hello World: [Tom] xxx"}}
----

== Additional Orchestration Capability Details

None

== Functional Requirements

* The capability will return a Hello World message. This capability will be a reference of the basic APIs needed to get a service implemented. 

== Non Functional Requirements

* SLA/QoS
 - N/A

* Security
 - N/A
