////////////////////////////////////////////////////////////////////////////////
Copyright (c) 2012, THE BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIOR UNIVERSITY
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   Neither the name of the STANFORD UNIVERSITY nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////

= Cyclades (Κυκλάδες) Service Engine

.STROMA/X-STROMA Compliant Service Engine Implementation

* link:cyclades_engine_installation.html[Cyclades Service Engine Installation Instructions]
* link:nyxlet_template_generation.html[Nyxlet Template Generation Instructions]
* link:nyxlet_agile_deployment_mechanisms.html[Nyxlet Agile Deployment Mechanisms]
* link:service_orchestration_examples.html[Advanced Service Orchestration Examples]
// * link:services/service_registry.html[Distribution Service Registry (examples)]
* link:nyxlet_lifecycle_management.html[Nyxlet Lifecycle Management Mechanisms]
* link:nyxlet_logging_mechanisms.html[Nyxlet Logging Mechanisms]
* link:nyxlet_input_validation.html[Nyxlet Input Validation Mechanisms]
* link:cyclades-engine-javadoc/index.html[Cyclades Engine API Documentation]
* link:cyclades_service_engine.html[Cyclades Technical Specification]
* link:STROMA_X-STROMA.html[STROMA/X-STROMA Specification]
* link:functional_view/functional_spec.html[User's Guide/Cyclades Functional Specification]
